### ISSUE TITLE
Running test programs using GrovePi+ board from idle Python 2 or 3 

### ISSUE THREAD

**Issue by oliwinkler** [DexterInd/GrovePi#105]
I can run without problem athe test program grove_relay.py from the command line : sudo python grove_relay.py

When I want to run it from idle python I get an error message when doing an import grovepi

bus = smbus-SMBus(1)
IOError: [Erno 13] Permission denied. .......

Questions
a) How to run from the command line python grove_relay.py not as SUDO?
or
b) from Idle,  python grove_relay.py  as SUDO when Running the program?

How to set up the corresponding right?

Thank you

Olivier

**Comment by kickapoo** [comment]
You need to be root user to access GPIO. 

Try to set grant root access:
`sudo usermod -a -G sudo <username>`

You need to log off and re-enter in order to take affect.

**Comment by karan259** [comment]
To grant access to the I2C to user pi, use:
```sudo adduser pi i2c```
