### ISSUE TITLE
GrovePI Humidity in C#

### ISSUE THREAD

**Issue by tonidy** [DexterInd/GrovePi#111]
I have tried the C# example and I could get the temperature value with temperature & humidity sensor. How to access humidity value from the sensor? I couldn't find any method to get the humidity value.

Thanks

**Comment by skdola** [comment]
same problem i am facing, how to pass command, can some one help here. for temperature we need to pass command 3 for humidity we need to pass 5.

**Comment by ser1us** [comment]
Also noticed it's missing, any updates on this issue?

**Comment by DexterInd** [comment]
Hey folks, example is now here:  https://github.com/DexterInd/GrovePi/tree/master/Software/CSharp/Samples/Example-Temp_and_Humidity

the example reads both the temp and the humidity.
