### ISSUE TITLE
Version mismatch with Microsoft.VCLib

### ISSUE THREAD

**Issue by dcaro** [DexterInd/GrovePi#157]
I have just downloaded the Visual Studio Project won VS2015 + Windows 10 up to date and I have the following error message.

DEP0810 : This app references Microsoft.VCLibs.140.00.Debug, version 14.0.22929.0, found in your SDK, but you have a higher version of Microsoft.VCLibs.140.00.Debug installed on the target machine, 14.0.23019.0. If you continue to run this application, it will run against the currently installed version, Microsoft.VCLibs.140.00.Debug, version 14.0.23019.0. Consider updating your SDK to match the version of Microsoft.VCLibs.140.00.Debug that is installed.

**Comment by DexterInd** [comment]
This should be solved now.
