### ISSUE TITLE
Not able to install npm package on Visual Studio

### ISSUE THREAD

**Issue by rhtnryn** [DexterInd/GrovePi#172]
@marcellobarile 

====Executing command 'npm install node-grovepi --save '====
npm WARN package.json DemoNodeApp@0.0.0 No repository field.
npm WARN package.json DemoNodeApp@0.0.0 No README data
npm WARN package.json DemoNodeApp@0.0.0 No license field.

> buffertools@2.1.3 install C:\Users\Rohit Narayan\documents\visual studio 2015\Projects\DemoNodeApp\DemoNodeApp\node_modules\node-grovepi\node_modules\buffertools
> node-gyp rebuild
> C:\Users\Rohit Narayan\documents\visual studio 2015\Projects\DemoNodeApp\DemoNodeApp\node_modules\node-grovepi\node_modules\buffertools>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 
> Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
>   buffertools.cc
> c:\users\rohit narayan\documents\visual studio 2015\projects\demonodeapp\demonodeapp\node_modules\node-grovepi\node_modules\buffertools\BoyerMoore.h(35): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data [C:\Users\Rohit Narayan\documents\visual studio 2015\Projects\DemoNodeApp\DemoNodeApp\node_modules\node-grovepi\node_modules\buffertools\build\buffertools.vcxproj]
> c:\users\rohit narayan\documents\visual studio 2015\projects\demonodeapp\demonodeapp\node_modules\node-grovepi\node_modules\buffertools\BoyerMoore.h(57): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data [C:\Users\Rohit Narayan\documents\visual studio 2015\Projects\DemoNodeApp\DemoNodeApp\node_modules\node-grovepi\node_modules\buffertools\build\buffertools.vcxproj]
> c:\users\rohit narayan\documents\visual studio 2015\projects\demonodeapp\demonodeapp\node_modules\node-grovepi\node_modules\buffertools\BoyerMoore.h(61): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [C:\Users\Rohit Narayan\documents\visual studio 2015\Projects\DemoNodeApp\DemoNodeApp\node_modules\node-grovepi\node_modules\buffertools\build\buffertools.vcxproj]
> c:\users\rohit narayan\documents\visual studio 2015\projects\demonodeapp\demonodeapp\node_modules\node-grovepi\node_modules\buffertools\BoyerMoore.h(61): warning C4267: 'initializing': conversion from 'size_t' to 'const int', possible loss of data [C:\Users\Rohit Narayan\documents\visual studio 2015\Projects\DemoNodeApp\DemoNodeApp\node_modules\node-grovepi\node_modules\buffertools\build\buffertools.vcxproj]
> c:\users\rohit narayan\documents\visual studio 2015\projects\demonodeapp\demonodeapp\node_modules\node-grovepi\node_modules\buffertools\BoyerMoore.h(62): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [C:\Users\Rohit Narayan\documents\visual studio 2015\Projects\DemoNodeApp\DemoNodeApp\node_modules\node-grovepi\node_modules\buffertools\build\buffertools.vcxproj]
> c:\users\rohit narayan\documents\visual studio 2015\projects\demonodeapp\demonodeapp\node_modules\node-grovepi\node_modules\buffertools\BoyerMoore.h(62): warning C4267: 'initializing': conversion from 'size_t' to 'const int', possible loss of data [C:\Users\Rohit Narayan\documents\visual studio 2015\Projects\DemoNodeApp\DemoNodeApp\node_modules\node-grovepi\node_modules\buffertools\build\buffertools.vcxproj]
> c:\users\rohit narayan\documents\visual studio 2015\projects\demonodeapp\demonodeapp\node_modules\node-grovepi\node_modules\buffertools\BoyerMoore.h(110): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data [C:\Users\Rohit Narayan\documents\visual studio 2015\Projects\DemoNodeApp\DemoNodeApp\node_modules\node-grovepi\node_modules\buffertools\build\buffertools.vcxproj]
> ..\buffertools.cc(219): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [C:\Users\Rohit Narayan\documents\visual studio 2015\Projects\DemoNodeApp\DemoNodeApp\node_modules\node-grovepi\node_modules\buffertools\build\buffertools.vcxproj]
> ..\buffertools.cc(219): warning C4267: 'initializing': conversion from 'size_t' to 'const int', possible loss of data [C:\Users\Rohit Narayan\documents\visual studio 2015\Projects\DemoNodeApp\DemoNodeApp\node_modules\node-grovepi\node_modules\buffertools\build\buffertools.vcxproj]
> ..\buffertools.cc(220): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [C:\Users\Rohit Narayan\documents\visual studio 2015\Projects\DemoNodeApp\DemoNodeApp\node_modules\node-grovepi\node_modules\buffertools\build\buffertools.vcxproj]
> ..\buffertools.cc(220): warning C4267: 'initializing': conversion from 'size_t' to 'const int', possible loss of data [C:\Users\Rohit Narayan\documents\visual studio 2015\Projects\DemoNodeApp\DemoNodeApp\node_modules\node-grovepi\node_modules\buffertools\build\buffertools.vcxproj]
> ..\buffertools.cc(332): warning C4267: '=': conversion from 'size_t' to 'int32_t', possible loss of data [C:\Users\Rohit Narayan\documents\visual studio 2015\Projects\DemoNodeApp\DemoNodeApp\node_modules\node-grovepi\node_modules\buffertools\build\buffertools.vcxproj]
> ..\buffertools.cc(334): warning C4267: '=': conversion from 'size_t' to 'int32_t', possible loss of data [C:\Users\Rohit Narayan\documents\visual studio 2015\Projects\DemoNodeApp\DemoNodeApp\node_modules\node-grovepi\node_modules\buffertools\build\buffertools.vcxproj]
> ..\buffertools.cc(340): warning C4244: 'argument': conversion from 'const ptrdiff_t' to 'int32_t', possible loss of data [C:\Users\Rohit Narayan\documents\visual studio 2015\Projects\DemoNodeApp\DemoNodeApp\node_modules\node-grovepi\node_modules\buffertools\build\buffertools.vcxproj]
> ..\buffertools.cc(419): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data [C:\Users\Rohit Narayan\documents\visual studio 2015\Projects\DemoNodeApp\DemoNodeApp\node_modules\node-grovepi\node_modules\buffertools\build\buffertools.vcxproj]
>   win_delay_load_hook.c
>      Creating library C:\Users\Rohit Narayan\documents\visual studio 2015\Projects\DemoNodeApp\DemoNodeApp\node_modules\node-grovepi\node_modules\buffertools\build\Release\buffertools.lib and object C:\Users\Rohit Narayan\documents\visual studio 2015\Projects\DemoNodeApp\DemoNodeApp\node_modules\node-grovepi\node_modules\buffertools\build\Release\buffertools.exp
>   Generating code
>   Finished generating code
>   buffertools.vcxproj -> C:\Users\Rohit Narayan\documents\visual studio 2015\Projects\DemoNodeApp\DemoNodeApp\node_modules\node-grovepi\node_modules\buffertools\build\Release\buffertools.node
> sleep@3.0.0 install C:\Users\Rohit Narayan\documents\visual studio 2015\Projects\DemoNodeApp\DemoNodeApp\node_modules\node-grovepi\node_modules\sleep
> node-gyp rebuild
> C:\Users\Rohit Narayan\documents\visual studio 2015\Projects\DemoNodeApp\DemoNodeApp\node_modules\node-grovepi\node_modules\sleep>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 
> Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
>   sleep.cc
>   win_delay_load_hook.c
>      Creating library C:\Users\Rohit Narayan\documents\visual studio 2015\Projects\DemoNodeApp\DemoNodeApp\node_modules\node-grovepi\node_modules\sleep\build\Release\node_sleep.lib and object C:\Users\Rohit Narayan\documents\visual studio 2015\Projects\DemoNodeApp\DemoNodeApp\node_modules\node-grovepi\node_modules\sleep\build\Release\node_sleep.exp
>   Generating code
>   Finished generating code
>   node_sleep.vcxproj -> C:\Users\Rohit Narayan\documents\visual studio 2015\Projects\DemoNodeApp\DemoNodeApp\node_modules\node-grovepi\node_modules\sleep\build\Release\node_sleep.node
> i2c-bus@0.11.3 install C:\Users\Rohit Narayan\documents\visual studio 2015\Projects\DemoNodeApp\DemoNodeApp\node_modules\node-grovepi\node_modules\i2c-bus
> node-gyp rebuild
> C:\Users\Rohit Narayan\documents\visual studio 2015\Projects\DemoNodeApp\DemoNodeApp\node_modules\node-grovepi\node_modules\i2c-bus>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 
> Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
>   i2c.cc
> c:\users\rohit narayan\documents\visual studio 2015\projects\demonodeapp\demonodeapp\node_modules\node-grovepi\node_modules\i2c-bus\src./i2c-dev.h(26): fatal error C1083: Cannot open include file: 'linux/types.h': No such file or directory [C:\Users\Rohit Narayan\documents\visual studio 2015\Projects\DemoNodeApp\DemoNodeApp\node_modules\node-grovepi\node_modules\i2c-bus\build\i2c.vcxproj]
> gyp ERR! build error 
> gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
> gyp ERR! stack     at emitTwo (events.js:87:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
> gyp ERR! System Windows_NT 10.0.10240
> gyp ERR! command "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\Rohit Narayan\documents\visual studio 2015\Projects\DemoNodeApp\DemoNodeApp\node_modules\node-grovepi\node_modules\i2c-bus
> gyp ERR! node -v v4.2.2
> gyp ERR! node-gyp -v v3.0.3
> gyp ERR! not ok 
> npm ERR! Windows_NT 10.0.10240
> npm ERR! argv "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "node-grovepi" "--save"
> npm ERR! node v4.2.2
> npm ERR! npm  v2.14.7
> npm ERR! code ELIFECYCLE
> npm ERR! i2c-bus@0.11.3 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the i2c-bus@0.11.3 install script 'node-gyp rebuild'.
> npm ERR! This is most likely a problem with the i2c-bus package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls i2c-bus
> npm ERR! There is likely additional logging output above.
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Users\Rohit Narayan\documents\visual studio 2015\Projects\DemoNodeApp\DemoNodeApp\npm-debug.log
> ====npm command completed with exit code 1====

**Comment by marcellobarile** [comment]
Hi @rhtnryn,
could you please tell me more about the environment of your project?

**Comment by rhtnryn** [comment]
This is a universal windows platform application project based on Node.js for Windows IoT core and I'm using Visual Studio 2015 IDE.

**Comment by marcellobarile** [comment]
Are you running it on a Raspberry Pi?

**Comment by rhtnryn** [comment]
Yes, the project has to be deployed on Raspberry Pi.

**Comment by marcellobarile** [comment]
To be honest I've never wrote applications for the RPi with the Visual Studio so I don't really know the workflow... I'm just trying to understand if you are getting this error on a RPi or on a Personal Computer. From your log I can clearly see that there are some troubles during the compiling of the I2C library:

i2c.cc
c:\users\rohit narayan\documents\visual studio 2015\projects\demonodeapp\demonodeapp\node_modules\node-grovepi\node_modules\i2c-bus\src./i2c-dev.h(26): fatal error C1083: Cannot open include file: 'linux/types.h': No such file or directory [C:\Users\Rohit Narayan\documents\visual studio

**Comment by rhtnryn** [comment]
i'm getting this error on my personal computer

**Comment by marcellobarile** [comment]
You can develop your Node application whenever you want but, after that, you should run it on your RPi (because you are going to use some hardware which is absent on your Personal Computer). I don't know your skill level on Node.js but you can easily install the application through  the "npm install" command after having created a package.json file (with dependencies etc...)

Let me know if you need further informations.

Have a good day
