### ISSUE TITLE
The purpose of purging and reinstalling python-rpi

### ISSUE THREAD

**Issue by alan-martinovic** [DexterInd/GrovePi#189]
In the install script, why do you purge and later reinstall python-rpi?

https://github.com/DexterInd/GrovePi/blob/master/Script/install.sh#L68

**Comment by karan259** [comment]
there was a very old version of the python-rpi that was incompatible with our libraries and made our libraries crash. Since the script is a part of the update process, we just make sure that the python-rpi and python3-rpi are the latest ones

**Comment by alan-martinovic** [comment]
Thanks :)
Why is it installed from both apt repos and pip?
https://github.com/DexterInd/GrovePi/blob/master/Script/install.sh#L72
