### ISSUE TITLE
Need GrovePi?

### ISSUE THREAD

**Issue by jedi0605** [DexterInd/GrovePi#193]
Hello, 
I'm buy
http://www.seeedstudio.com/wiki/Grove_-_OLED_Display_1.12%22
for my RaspberryPi.
If I want use "OLED_Display_1.12", is necessary buy GrovePi?
Or I can use OLED display with I2C socket connect to Raspberry Pi without GrovePi?

**Comment by DexterInd** [comment]
Not sure.  You can always hack together your own connections, but there's no way to plug and play the OLED Display into the Raspberry Pi.
