### ISSUE TITLE
grove_gps.py file output incorrect decimal degrees format

### ISSUE THREAD

**Issue by TxEdgeMan** [DexterInd/GrovePi#208]
Hi,

While the latitude and longitude coordinates in decimal degrees is in the correct format on the screen, the decimal is moved to the left 2 positions in the output file, making them invalid decimal degree values.

Need to change:   
s=str(t)+","+str(float(lat)**/100**)+","+str(float(long)**/100**)+"\n"

to 

s=str(t)+","+str(float(lat))+","+str(float(long))+"\n"

thanks,

Chris

**Comment by DexterInd** [comment]
Updated.  Can you check it!  Thanks!
