### ISSUE TITLE
Ruby

### ISSUE THREAD

**Issue by ollieatkinson** [DexterInd/GrovePi#211]
Is building a ruby framework on the timeline for GrovePi?

**Comment by DexterInd** [comment]
Hey @ollieatkinson , no one has stepped up to do it yet unfortunately.  Any interest?

**Comment by ollieatkinson** [comment]
I will have a look at the requirements of interacting in ruby.

**Comment by ollieatkinson** [comment]
ref:

https://firmhouse.com/blog/wrapping-up-a-c-library-for-ruby-it-s-actually-pretty-easy/
http://tenderlovemaking.com/2010/12/11/writing-ruby-c-extensions-part-2.html

**Comment by DexterInd** [comment]
Thanks for taking a look at this @ollieatkinson

**Comment by RobertLucian** [comment]
A library in Ruby written by @iia has just been added in PR #388 . Closing this now.
