### ISSUE TITLE
RF Receiver and RF Transmitter

### ISSUE THREAD

**Issue by Patafoin** [DexterInd/GrovePi#242]
Hello,

Is it possible to add RF Receiver and RF Transmitter modules to the C# library please ?
Thanks
Steeve

**Comment by karan259** [comment]
Hey @Patafoin did the python examples work for you?

**Comment by Patafoin** [comment]
Hi Karan,

I asked for C#, not python :( So, no, there's nothing working at this moment.
I think the grovepi firmware should be updated with the RC-Switch Library to handle RF.

**Comment by DexterInd** [comment]
Hey @Patafoin we have no plans to add these devices any time soon, I'm sorry.
