### ISSUE TITLE
upgrading grovepi firmware from windows

### ISSUE THREAD

**Issue by Patafoin** [DexterInd/GrovePi#243]
Hi,

I would like to participate to the grovepi github but I would like to upgrade my firmware.
Is there a way to do that from a windows machine ? I saw no documentation about that.
Thanks

**Comment by DexterInd** [comment]
Hey @Patafoin , unfortunately the only way to update the firmware is with Raspbian for Robots right now.  This option is not available with WinIoT.  Yet.
