### ISSUE TITLE
Unattended install script

### ISSUE THREAD

**Issue by willemdh** [DexterInd/GrovePi#244]
Following this procedure => http://www.dexterindustries.com/GrovePi/get-started-with-the-grovepi/setting-software/

Is there a way to make the install script unattended, so that I don't have to confirm installation? For example with a -y parameter?

    Do you want to continue? [Y/n]

**Comment by CleoQc** [comment]
That tutorial is a bit out of date. The script *should* be ok to run unattended.
Did you encounter a place where it stopped?

**Comment by CleoQc** [comment]
Pull request #245
This should help a bit. Thanks for flagging it!

**Comment by DexterInd** [comment]
Thanks @CleoQc for solving this!

**Comment by willemdh** [comment]
Thanks all. Installing right now and seems to continue without asking for confirmation. :)
