### ISSUE TITLE
dustDigitalSensor.js Don't work 

### ISSUE THREAD

**Issue by SunHaoli** [DexterInd/GrovePi#263]
I want to drive Grove Dust Sensor wit NodeJS.
But in the present dustDigitalSensor.js the algorithm seems differs from the example in [http://www.howmuchsnow.com/arduino/airquality/grovedust/](http://www.howmuchsnow.com/arduino/airquality/grovedust/) and
[http://www.seeedstudio.com/wiki/images/4/4c/Grove_-_Dust_sensor.pdf](http://www.seeedstudio.com/wiki/images/4/4c/Grove_-_Dust_sensor.pdf)
The code in dustDigitalSensor.js:
`if (write) {
    this.board.wait(200)
    this.board.readByte()
    var bytes = this.board.readBytes()
    if (bytes instanceof Buffer && bytes[1] != 255)
      return [bytes[1], (bytes[4] * 256 * 256 + bytes[3] * 256 + bytes[2])]`
It calculates the value of some bytes, but in the Specification sheet Low pulse occupancy is required to be calculated. So the current dustDigitalSensor.js seems to be not right.

So I wrote my own driver, I get the first byte (0 or 1) and the current time stamp from the sensor, and calculate the occupancy time of '0'.
`function start() {
    console.log('starting');

```
board = new Board({
    debug: true,
    onError: function(err) {
        console.log('Error');
        console.log(err);
    },

    onInit: function(res) {
        var dustSensor = new DustDigitalSensor(3); //digital port 3
        console.log('GrovePi Version :: ' + board.version());
        var lowpulseoccupancy = 0;
        var duration = 0;
        var sample_time_ms = 30000; //30s
        var ratio = 0;
        var t1 = 0;
        var t2 = 0;
        var flag = false;
        if(res) {
            var t_start = process.uptime() * 1000;
            console.log('Dust Digital Sensor (start watch)');
            dustSensor.on('change', function(res) {
                if (res[0] == 1 && t1 !== 0 && flag) {
                    t2 = res[1];
                    duration = t2 - t1;
                    lowpulseoccupancy = lowpulseoccupancy + duration;
                    flag = false;
                }else if (res[0] == 0) {
                    t1 = res[1];
                    flag = true;
                }

                if (res[1] - t_start >= sample_time_ms) {  //if reaches 30s
                    ratio = (lowpulseoccupancy/sample_time_ms) * 100;   //get percentage between 0 and 100
                    concentration = 1.1 * Math.pow(ratio, 3) - 3.8 * Math.pow(ratio, 2) + 520*ratio + 0.62  //using spec sheet curve
                    console.log('concentration = ' + concentration + ' pcs/0.01cf');
                    lowpulseoccupancy = 0;
                    t_start = res[1]; 
                }
            });
            dustSensor.watch();
        }else {
            console.log('CANNOT START');
          }
    }
});
board.init();
```

}` 

Hope this may help.

**Comment by marcellobarile** [comment]
Hi @SunHaoli,
thank you so much for your contribution. I'll check if the specs. has been changed or if something wrong has happened, by the way I'll definitely include your solution in a next release.

For any further informations don't hesitate to contact me.
Have a nice day
