### ISSUE TITLE
Sensor values for IFTTT

### ISSUE THREAD

**Issue by amiransari** [DexterInd/GrovePi#271]
Hey there,

Thanks for your content re the Grove Gesture module. I'm using the SEEED WIO Link modules together with IFTTT to control some output sensors. However, for IFTTT, I don't know what the numerical values for the 9 gestures are.  Any help would be appreciated.

**Comment by karan259** [comment]
@amiransari : here is the list of what each gesture value means: https://github.com/DexterInd/GrovePi/blob/master/Software/Python/grove_gesture_sensor/grove_gesture_sensor.py#L467-L477
