### ISSUE TITLE
Windows 10 Iot - HomeWeatherDisplay c# not returning correct temp

### ISSUE THREAD

**Issue by bbSkygazer** [DexterInd/GrovePi#301]
All code complies and executes however number returned by temphumidity sensor is incorrect.

For example at 23C in my house the data returned in 5.02C consistently.

**Comment by bbSkygazer** [comment]
All fixed. The problem was that the instruction say to plug DHT into D7 but the code references D3. So I changed to code to D7 and all works.

**Comment by DexterInd** [comment]
Could you kindly send an updated PR?  Not sure where the instructions said D7?
