### ISSUE TITLE
Is it possible to slave an arduino for motors and servos while Grove Pi hat is on?

### ISSUE THREAD

**Issue by ghettokon** [DexterInd/GrovePi#339]
Thanks,

**Comment by RobertLucian** [comment]
Hi @ghettokon,

Can you please post this issue on our forums?
Here's a link to our `GrovePi` forums: http://forum.dexterindustries.com/c/grovepi

Also, by posting on the forum instead, other users may benefit from it. So it's a win-win situation.

Last but not least, can you come up with more details about what you're trying to accomplish? Screenshots, circuit diagrams, code lines, basically anything technical is well received. 
The more detailed is your issue, the better we can understand it and solve it faster.

Thank you!
