### ISSUE TITLE
Unable to select suitable driver for this board

### ISSUE THREAD

**Issue by LuCavallin** [DexterInd/GrovePi#349]
More details here: http://forum.dexterindustries.com/t/grove-dht-and-golang-in-general/3187
Do you think it's my code or your library?
i2cdetect returns the expected result!

**Comment by DexterInd** [comment]
Hey @LuCavallin going to close this since we're talking about it on the forums [and over here](https://github.com/DexterInd/GrovePi/pull/9#issuecomment-308543477).

**Comment by LuCavallin** [comment]
Ah yeah, I guess I duplicated the post for some reason. Thanks!

**Comment by LuCavallin** [comment]
Solved here: https://github.com/mrmorphic/hwio/issues/49
