### ISSUE TITLE
fix broken go examples

### ISSUE THREAD

**Issue by sclausen** [DexterInd/GrovePi#352]
38fec748dc13819c293eeb4d019825d8bf884c74 broke the go examples

**Comment by DexterInd** [comment]
@sclausen what's happening when you try now?  

@LuCavallin can you hop in here?

**Comment by LuCavallin** [comment]
I see, I've updated the library but not the example code.
Tonight I can update the library again and fix the example.
If I forget, just send me a message.

**Comment by sclausen** [comment]
@DexterInd It simply doesn't compile, since the API changed. Nothing serious.
