### ISSUE TITLE
Home_Weather_Display Project needs a delay

### ISSUE THREAD

**Issue by keebie81** [DexterInd/GrovePi#362]
The code for this project does not have a delay. This causes the lcd to constantly refresh and become unreadable.

**Comment by RobertLucian** [comment]
I think I know what's to be done. I'll be back with a `PR`. 
Will keep in touch with you.

Thanks!

**Comment by RobertLucian** [comment]
@keebie81 
I've brought a couple of changes.
Everything should be good.

I'm now making a PR.
