### ISSUE TITLE
dust_sensor_en

### ISSUE THREAD

**Issue by yashwantptl7** [DexterInd/GrovePi#449]
when I run grove_dust_sensor code , it is getting stuck at 
`def dust_sensor_en(pin = 2):
	write_i2c_block(dust_sensor_en_cmd + [pin, unused, unused])
	read_i2c_block(no_bytes = 1)
`
segment of grovepi.py....Here it is unable to execute write_i2c_block....Also can someone explain this segment to me

Thanks

**Comment by RobertLucian** [comment]
This happens when the running firmware is not compatible with the drivers on the Raspberry Pi. I'm closing this down.
