### ISSUE TITLE
Connecting Grove GPS with Grove Base HAT (for RPi)

### ISSUE THREAD

**Issue by RattleRat** [DexterInd/GrovePi#462]
Hi, may I know if it is possible to connect the Grove GPS to the Grove Base HAT?

Are the any codes for it or modifications required?

What I have found so far is DexterGPS.py that functions with the GrovePi an d also to change the UART configurations.

**Comment by CleoQc** [comment]
The Grove Base HAT is manufactured by SEEED and not by Dexter Industries. We are not familiar with that particular HAT. Sorry
