### ISSUE TITLE
Installing on balena.io or docker

### ISSUE THREAD

**Issue by wojciechczyz** [DexterInd/GrovePi#473]
How can we install software on balena.io to be able to update firmware remotely and use the board.?

**Comment by CleoQc** [comment]
I have no experience with balena.io unfortunately.
You can try this: 
`curl -kL dexterindustries.com/update_grovepi | bash -s -- --bypass-gui-installation  --env-local --install-python-package`

This is what we recommend for virtual environments. Hopefully it will also work for Docker.
