### ISSUE TITLE
Remove Accelerometer and RTC from Firmware

### ISSUE THREAD

**Issue by karan259** [DexterInd/GrovePi#60]
Remove RTC and accelerometer from the firmware since they are I2C devices and can be directly accessed from the Pi

**Comment by mcauser** [comment]
It's also just the MMC7660 +/-1.5g sensor. There are a few others too. +/-16g, +/-400g

**Comment by karan259** [comment]
Hey Mike,
We need to add support for these in the SOftware only, right

**Comment by mcauser** [comment]
Yeah, drop it from the Arduino firmware, add Python I2C examples.
