### ISSUE TITLE
Add support for Grove Chainable RGB LED

### ISSUE THREAD

**Issue by mcauser** [DexterInd/GrovePi#61]
http://www.seeedstudio.com/depot/Grove-Chainable-RGB-LED-p-850.html

**Comment by mcauser** [comment]
http://www.dexterindustries.com/forum/?topic=support-for-grove-chainable-rgb-led

**Comment by karan259** [comment]
Hey Mike,
Any update on this. Do you think that it would be better to cleanup and optimize the firmware source, i.e., go for 1.3 and then add the support for it or before that

**Comment by mcauser** [comment]
See PR: https://github.com/DexterInd/GrovePi/pull/68

**Comment by mcauser** [comment]
https://github.com/DexterInd/GrovePi/blob/master/Firmware/Source/v1.2/grove_pi_v1_2_2/README.md

**Comment by BandonRandon** [comment]
Does  3be4d0c close this?

**Comment by karan259** [comment]
Yeah, the grove RGB led's now work. There is another issue with connecting multiple sensors. You can read more about it here: https://github.com/DexterInd/GrovePi/issues/180

**Comment by mcauser** [comment]
I have 10x Grove RGB LEDs. I'll do some debugging. It's a 4 wire module, (data, clock, vcc, gnd) so if you are using D4, you must keep D5 empty as it shares a pin.
