### ISSUE TITLE
Add support for Grove LED Bar

### ISSUE THREAD

**Issue by mcauser** [DexterInd/GrovePi#62]
http://www.seeedstudio.com/depot/Grove-LED-Bar-p-1178.html

**Comment by mcauser** [comment]
https://github.com/DexterInd/GrovePi/pull/52

**Comment by mcauser** [comment]
http://www.dexterindustries.com/forum/?topic=support-for-led-bar

**Comment by mcauser** [comment]
https://github.com/DexterInd/GrovePi/tree/master/Firmware/Source/v1.2/grove_pi_v1_2_0

**Comment by karan259** [comment]
we'll cleanup the hex folder and release this ASAP

**Comment by DexterInd** [comment]
@karan259  status?  Close this?

**Comment by karan259** [comment]
yeah, closing this. Has been integrated
